# Site Settings
baseurl: ""
url : "https://cherylouyang.github.io/"

# Blog Settings
theme_settings :
  title : Grape Theme
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : Cheryl Ouyang
    description : just a gal trying to set up her own website
    experience :
      - start : 2017-05-03
        end : 2018-05-06
        experience : company name, title
    skills : 
      - skill : HTML5 & CSS
        value : 85  # Percent value
        
  # Icons
  icons :
    email:  # Full email address, e.g. "sample@google.com"
    linkedin:  # Full URL 
    github: cherylouyang
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
