# Site Settings
baseurl: ""
url : "https://cherylouyang.github.io/"

# Blog Settings
theme_settings :
  title : Cheryl Ouyang
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : Cheryl Ouyang
    description : just a gal exploring the realm of software & technology
    experience :
      - start : 2022/01
        end : 2022/02
        experience : Deloitte, Forensic Technology Intern
      - start : 2021/11
        end : 2021/12
        experience : McGrathNicol, Cyber & Forensic Technology Intern
      - start : 2020/10
        end : 2021/11
        experience : UNSW Digital Society, Vice President Operations
      - start : 2020/01
        end : 2020/10
        experience : UNSW Digital Society, Digital Director
    skills : 
      - skill : Python
        value : 90  # Percent value
      - skill : C
        value : 85  # Percent value
    languages : 
      - skill : English
        value : 100  # Percent value
      - skill : Chinese (Mandarin)
        value : 90  # Percent value
      - skill : Chinese (Cantonese)
        value : 80  # Percent value
      - skill : Spanish
        value : 20  # Percent value
        
  # Icons
  icons :
    email:  # Full email address, e.g. "sample@google.com"
    linkedin: https://www.linkedin.com/in/cheryl-ouyang/ # Full URL 
    github: cherylouyang
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
